const getState = ({ getStore, getActions, setStore }) => {
  return {
    store: {
      cart: [],
      carModels: [
        {
          brakeModel: 8284,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/8284/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/8284/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/8284/3.png"],
          type: "Semimetálica",
          brand: "Volkswagen",
          model: "Gol",
          initialYear: 1998,
          position: "Delanteras",
          price: 10,
          quantity: 90,
          id: 1,
          "Imagen de carro": "X",
          ML: "X",
          IG: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Gol1998.png",
        },
        {
          brakeModel: 8284,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/8284/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/8284/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/8284/3.png"],
          type: "Semimetálica",
          brand: "Chevrolet",
          model: "Corsa",
          initialYear: 1998,
          finalYear: 2001,
          position: "Delanteras",
          price: 10,
          quantity: 90,
          id: 2,
          "Imagen de carro": "X",
          ML: "X",
          IG: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Corsa2000.png",
        },
        {
          brakeModel: 4465,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/04465/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/04465/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/04465/3.png"],
          type: "Cerámica",
          brand: "Toyota",
          model: "Hilux 4x4",
          position: "Delanteras",
          price: 20,
          quantity: 58,
          id: 3,
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Hilux2008DC.png",
        },
        {
          brakeModel: 7639,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7639/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7639/2.png"],
          type: "Cerámica",
          brand: "Toyota",
          model: "Machito",
          initialYear: 1998,
          finalYear: 2006,
          Característica: "Chasis largo (98-07)",
          position: "Delanteras",
          price: 25,
          quantity: 17,
          id: 4,
          "Imagen de carro": "X",
          ML: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/MachitoChasisLargo2000.png",
        },
        {
          brakeModel: 8335,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/8335/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/8335/2.png"],
          type: "Cerámica",
          brand: "Toyota",
          model: "Corolla",
          initialYear: 2004,
          finalYear: 2009,
          Característica: "New Sensation",
          position: "Delanteras",
          price: 25,
          quantity: 14,
          id: 5,
          "Imagen de carro": "X",
          ML: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/CorollaNewSensation2008.png",
        },
        {
          brakeModel: 7877,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/3.png"],
          type: "Cerámica",
          brand: "Toyota",
          model: "4Runner",
          initialYear: 2003,
          finalYear: 2009,
          position: "Delanteras",
          price: 30,
          quantity: 26,
          id: 6,
          "Imagen de carro": "X",
          ML: "X",
          IG: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/4Runner2005.png",
        },
        {
          brakeModel: 7877,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/3.png"],
          type: "Cerámica",
          brand: "Toyota",
          model: "FJ Cruisser",
          initialYear: 2009,
          finalYear: 2009,
          position: "Delanteras",
          price: 30,
          quantity: 26,
          id: 7,
          "Imagen de carro": "X",
          ML: "X",
          IG: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/FJCruiser2009.png",
        },
        {
          brakeModel: 7877,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/3.png"],
          type: "Cerámica",
          brand: "Toyota",
          model: "Tacoma",
          initialYear: 2007,
          finalYear: 2008,
          position: "Delanteras",
          price: 30,
          quantity: 26,
          id: 8,
          "Imagen de carro": "X",
          ML: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Tacoma2007.png",
        },
        {
          brakeModel: 7877,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/3.png"],
          type: "Cerámica",
          brand: "Toyota",
          model: "Tundra",
          initialYear: 2002,
          finalYear: 2008,
          position: "Delanteras",
          price: 30,
          quantity: 26,
          id: 9,
          "Imagen de carro": "X",
          ML: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Tundra2002.png",
        },
        {
          brakeModel: 7877,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/3.png"],
          type: "Cerámica",
          brand: "Toyota",
          model: "Fortuner",
          initialYear: 2008,
          finalYear: 2011,
          position: "Delanteras",
          price: 30,
          quantity: 26,
          id: 10,
          "Imagen de carro": "X",
          ML: "X",
          IG: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Fortuner2010.png",
        },
        {
          brakeModel: 7877,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/3.png"],
          type: "Cerámica",
          brand: "Toyota",
          model: "Burbuja",
          initialYear: 2006,
          finalYear: 2009,
          position: "Delanteras",
          price: 30,
          quantity: 26,
          id: 11,
          "Imagen de carro": "X",
          IG: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Burbuja2000.png",
        },
        {
          brakeModel: 7877,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/3.png"],
          type: "Cerámica",
          brand: "Toyota",
          model: "Autana",
          initialYear: 2006,
          finalYear: 2009,
          position: "Delanteras",
          price: 30,
          quantity: 26,
          id: 12,
          "Imagen de carro": "X",
          IG: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Autana2008.png",
        },
        {
          brakeModel: 7877,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/3.png"],
          type: "Cerámica",
          brand: "Toyota",
          model: "Hilux  ",
          initialYear: 2006,
          finalYear: 2008,
          Característica: "Sencilla",
          position: "Delanteras",
          price: 30,
          quantity: 26,
          id: 13,
          "Imagen de carro": "X",
          ML: "X",
          IG: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Hilux2007CS.png",
        },
        {
          brakeModel: 7877,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/3.png"],
          type: "Cerámica",
          brand: "Toyota",
          model: "Hilux  ",
          initialYear: 2006,
          finalYear: 2010,
          Característica: "Doble Cabina",
          position: "Delanteras",
          price: 30,
          quantity: 26,
          id: 14,
          "Imagen de carro": "X",
          ML: "X",
          IG: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Hilux2008DC.png",
        },
        {
          brakeModel: 7877,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7877/3.png"],
          type: "Cerámica",
          brand: "Mitsubishi",
          model: "Montero",
          initialYear: 2009,
          finalYear: 2011,
          position: "Delanteras",
          price: 30,
          quantity: 26,
          id: 15,
          "Imagen de carro": "X",
          IG: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Montero2010.png",
        },
        {
          brakeModel: 7261,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7261/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7261/2.png"],
          type: "Semimetálica",
          brand: "Renault",
          model: "Twingo",
          initialYear: 2000,
          finalYear: 2007,
          position: "Delanteras",
          price: 10,
          quantity: 121,
          id: 16,
          "Imagen de carro": "X",
          ML: "X",
          IG: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Twingo2002.png",
        },
        {
          brakeModel: 7261,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7261/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7261/2.png"],
          type: "Semimetálica",
          brand: "Renault",
          model: "Symbol",
          initialYear: 2000,
          finalYear: 2007,
          position: "Delanteras",
          price: 10,
          quantity: 121,
          id: 17,
          "Imagen de carro": "X",
          ML: "X",
          IG: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Symbol2005.png",
        },
        {
          brakeModel: 7261,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7261/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7261/2.png"],
          type: "Semimetálica",
          brand: "Renault",
          model: "Clio",
          initialYear: 2000,
          finalYear: 2004,
          position: "Delanteras",
          price: 10,
          quantity: 121,
          id: 18,
          "Imagen de carro": "X",
          ML: "X",
          IG: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Clio2002.png",
        },
        {
          brakeModel: 7261,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7261/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7261/2.png"],
          type: "Semimetálica",
          brand: "Renault",
          model: "Megane",
          initialYear: 2000,
          finalYear: 2004,
          position: "Delanteras",
          price: 10,
          quantity: 121,
          id: 19,
          "Imagen de carro": "X",
          ML: "X",
          IG: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Megane2002.png",
        },
        {
          brakeModel: 7417,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7417/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7417/2.png"],
          type: "Semimetálica",
          brand: "Mitsubishi",
          model: "Lancer",
          initialYear: 1995,
          finalYear: 1998,
          position: "Delanteras",
          price: 10,
          quantity: 21,
          id: 20,
          "Imagen de carro": "X",
          ML: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Lancer1997.png",
        },
        {
          brakeModel: 7939,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7939/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7939/2.png"],
          type: "Semimetálica",
          brand: "Chevrolet",
          model: "Optra",
          initialYear: 2004,
          finalYear: 2013,
          position: "Traseras",
          price: 10,
          quantity: 17,
          id: 21,
          "Imagen de carro": "X",
          ML: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Optra2010.png",
        },
        {
          brakeModel: 7704,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7704/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7704/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7704/3.png"],
          type: "Semimetálica",
          brand: "Toyota",
          model: "Yaris",
          initialYear: 2000,
          finalYear: 2006,
          position: "Delanteras",
          price: 15,
          quantity: 4,
          id: 22,
          "Imagen de carro": "X",
          ML: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Yaris2004.png",
        },
        {
          brakeModel: 8266,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/8266/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/8266/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/8266/3.png"],
          type: "Semimetálica",
          brand: "Kia",
          model: "Rio",
          initialYear: 2009,
          finalYear: 2011,
          position: "Delanteras",
          price: 10,
          quantity: 8,
          id: 23,
          "Imagen de carro": "X",
          ML: "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Rio2010.png",
        },
        {
          brakeModel: 8385,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/8385/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/8385/2.png", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/8385/3.png"],
          type: "Semimetálica",
          brand: "Chevrolet",
          model: "Aveo",
          initialYear: 2007,
          finalYear: 2009,
          Característica: "LS",
          position: "Delanteras",
          price: 10,
          quantity: 3,
          id: 24,
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/AveoLS2007.png",
        },
        {
          brakeModel: 7298,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7298/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7298/2.png"],
          type: "Cerámica",
          brand: "Toyota",
          model: "Burbuja",
          initialYear: 1989,
          finalYear: 2005,
          position: "Delanteras",
          price: 20,
          quantity: 1,
          id: 25,
          "Imagen de carro": "X",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Burbuja2000.png",
        },
        {
          brakeModel: 7298,
          brakeImgs: ["https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7298/1.jpg", "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/Pastillas%20de%20freno/7298/2.png"],
          type: "Cerámica",
          brand: "Toyota",
          model: "4 Runner",
          initialYear: 1989,
          finalYear: 2003,
          position: "Delanteras",
          price: 20,
          quantity: 1,
          id: 26,
          "Imagen de carro": "O",
          img: "https://raw.githubusercontent.com/frako23/test-catalog/main/src/assets/img/4Runner2005.png",
        },
      ],
    },
    actions: {
      // Use getActions to call a function within a fuction
      exampleFunction: () => {
        getActions().changeColor(0, "green");
      },
      loadSomeData: () => {
        /**
					fetch().then().then(data => setStore({ "foo": data.bar }))
				*/
      },
      addToCart: (sku) => {
        //get the store
        const store = getStore();


        //reset the global store
        setStore({  cart: [...store.cart, sku] });
      },
      removeFromCart: (model) => {
        //get the store
        const store = getStore();
        //reset the global store
        setStore({  cart: store.cart.filter((item) => item.model !== model) });
      },
    },
  };
};

export default getState;  
